DATA SEGMENT
SOURCE DB 'absafdASDAasdaAIOc', '$'
COUNT EQU $-SOURCE
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
BEGIN:
    MOV AX,DATA
    MOV DS,AX
    MOV CX,COUNT
    LEA SI,SOURCE
L1: 
	MOV AL,[SI]
	AND AL,11011111B
    MOV [SI],AL
NEXT:
    INC SI
    LOOP L1
    MOV BYTE PTR [SI-1],'$'
    MOV AH,09H
    LEA DX,SOURCE
    INT 21H
    MOV AH,4CH
    INT 21H
CODE ENDS
    END BEGIN

