DATA SEGMENT
STRING DB 'ChenMingLiang', 0AH, '16340023', 0DH, 0AH, '$'
DATA ENDS

CODE SEGMENT
	ASSUME CS:CODE, DS:DATA
BEGIN:
	PUSH DS
	MOV AX, SEG INT_60H ;获取CS值
	MOV DS, AX
	MOV DX, OFFSET INT_60H ;获取IP值
	MOV AH, 25H ;装入系统调用表
	MOV AL, 60H
	INT 21H ;执行填装
	PUSH DS
	INT 60H ;开始调用INT 60H指令
	MOV AH, 4CH ;此处可以看到，若非成功调用，不会显示结果
	INT 21H

INT_60H:        ;INT 60H指令的中断调用子程序
	MOV AX, DATA
	MOV DS, AX
	MOV DX, OFFSET STRING
	MOV AH, 9
	INT 21H
	MOV AH, 4CH
	INT 21H
CODE ENDS
	END BEGIN