# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SingleCycleCPU.xdc

# Block Designs: bd/SingleCycleCPUDesign/SingleCycleCPUDesign.bd
# Block Designs: The module: 'SingleCycleCPUDesign' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/SingleCycleCPUDesign/ip/SingleCycleCPUDesign_clk_div_0_1/SingleCycleCPUDesign_clk_div_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SingleCycleCPUDesign_clk_div_0_1 || ORIG_REF_NAME==SingleCycleCPUDesign_clk_div_0_1}]

# IP: bd/SingleCycleCPUDesign/ip/SingleCycleCPUDesign_four_2_input_and_gate_0_0/SingleCycleCPUDesign_four_2_input_and_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SingleCycleCPUDesign_four_2_input_and_gate_0_0 || ORIG_REF_NAME==SingleCycleCPUDesign_four_2_input_and_gate_0_0}]

# IP: bd/SingleCycleCPUDesign/ip/SingleCycleCPUDesign_generSingal_0_0/SingleCycleCPUDesign_generSingal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SingleCycleCPUDesign_generSingal_0_0 || ORIG_REF_NAME==SingleCycleCPUDesign_generSingal_0_0}]

# IP: bd/SingleCycleCPUDesign/ip/SingleCycleCPUDesign_clk_div_1_0/SingleCycleCPUDesign_clk_div_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SingleCycleCPUDesign_clk_div_1_0 || ORIG_REF_NAME==SingleCycleCPUDesign_clk_div_1_0}]

# IP: bd/SingleCycleCPUDesign/ip/SingleCycleCPUDesign_bcdToseg7_0_0/SingleCycleCPUDesign_bcdToseg7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SingleCycleCPUDesign_bcdToseg7_0_0 || ORIG_REF_NAME==SingleCycleCPUDesign_bcdToseg7_0_0}]

# IP: bd/SingleCycleCPUDesign/ip/SingleCycleCPUDesign_SingleCycleCPU_0_0/SingleCycleCPUDesign_SingleCycleCPU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SingleCycleCPUDesign_SingleCycleCPU_0_0 || ORIG_REF_NAME==SingleCycleCPUDesign_SingleCycleCPU_0_0}]

# IP: bd/SingleCycleCPUDesign/ip/SingleCycleCPUDesign_SelectAndShow_0_0/SingleCycleCPUDesign_SelectAndShow_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SingleCycleCPUDesign_SelectAndShow_0_0 || ORIG_REF_NAME==SingleCycleCPUDesign_SelectAndShow_0_0}]

# XDC: bd/SingleCycleCPUDesign/SingleCycleCPUDesign_ooc.xdc
